services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      # Overridden with real credentials in compose.prod.yaml
      DATABASE_URL: mysql://${MYSQL_USER:-root}@database:3306/${MYSQL_DATABASE:-app}?serverVersion=${MYSQL_VERSION:-10.11}&charset=utf8mb4
      MAILER_DSN: ${MAILER_DSN:-smtp://mailer:1025}
      # The two next lines can be removed after initial installation
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - database
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-8000}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-8443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-8443}
        protocol: udp

volumes:
  caddy_data:
  caddy_config:
