services:
    sf:
        build: .docker/sf
        volumes:
            - ./:/var/www/app
        ports:
            - "8000:80"
        depends_on:
            - db
        user: www-data
        dns:
            - 8.8.8.8
            - 208.67.222.222
            - 1.1.1.1
    db:
        image: mariadb:10
        ports:
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: 'sf_dev'
    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "1025:1025"
            - "8025:8025"
    # encore:
    #     build: .docker/node
    #     volumes:
    #         - ./:/usr/src/app
    #     ports:
    #         - "8080:8080"
    #     depends_on:
    #         - sf
    #     environment: 
    #         - LOCAL_DOMAIN=sf/
    #     command: sh -c "npm run dev-server"
    #     user: node

    sass-watcher:
        build: .docker/sf
        volumes:
            - ./:/var/www/app
        ports:
            - "8088:80"
        user: www-data
        command: sh -c "php bin/console sass:build --watch"

    messenger-worker:
        build: .docker/sf
        volumes:
            - ./:/var/www/app
        ports:
            - "8089:80"
        depends_on:
            - db
        user: www-data
        command: sh -c "php bin/console messenger:consume"